services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./docker/sqlserver/scripts:/scripts
    entrypoint:
      - /bin/bash
      - /scripts/entrypoint.sh

  llama-cpp:
    build: ./docker/llama-cpp
    container_name: llama-cpp
    ports:
      - "8080:8080"
    volumes:
      - ./docker/llama-cpp/models:/models

volumes:
  sqlserver_data:
