services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./docker/sqlserver/scripts:/scripts
    entrypoint:
      - /bin/bash
      - /scripts/entrypoint.sh

  llama-cpp:
    build: ./docker/llama-cpp
    container_name: llama-cpp
    ports:
      - "8080:8080"
    volumes:
      - ./docker/llama-cpp/models:/models
    environment:
      # MODEL_FILE: llama-3.2-3b-instruct-q8_0.gguf
      # MODEL_URL: https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q8_0-GGUF/resolve/main/llama-3.2-3b-instruct-q8_0.gguf
      # MODEL_FILE: ELYZA-japanese-CodeLlama-7b-instruct-Q2_K.gguf
      # MODEL_URL: https://huggingface.co/tensorblock/ELYZA-japanese-CodeLlama-7b-instruct-GGUF/resolve/main/ELYZA-japanese-CodeLlama-7b-instruct-Q2_K.gguf
      MODEL_FILE: gemma-3-4b-it-qat-q4_0-japanese-imatrix-Q4_K_M.gguf
      MODEL_URL: https://huggingface.co/dahara1/gemma-3-4b-it-qat-japanese-imatrix/resolve/main/gemma-3-4b-it-qat-q4_0-japanese-imatrix-Q4_K_M.gguf

volumes:
  sqlserver_data:
